# Dependencies
markdown:         kramdown
kramdown:
  parse_block_html: true 

# Setup
title:            
tagline:          
description:      
url:              
baseurl:          /recipes


#Plugins
gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap
